import { useEffect, useRef, useState } from 'react';
import { branchPose, degrees, distance, forward, inverse, poseValid, radians, singularity, type Branch, type Pose } from './core/kinematics';
import { MAX_SAMPLES, motionSample, samplesCsv, totalMs } from './core/motion';
import { MAX_FILE_BYTES, MAX_WAYPOINTS, parseSession } from './core/session';
import { useSimulator } from './useSimulator';
import { NumberField } from './components/NumberField';
import { RobotCanvas } from './components/RobotCanvas';
import { ExportDialog, HelpDialog, SettingsDialog } from './components/Dialogs';
function Icon({ name }: {
    name: 'play' | 'pause' | 'stop' | 'save' | 'settings' | 'fit' | 'upload' | 'download';
}) {
    const paths = { play: 'M7 4 19 12 7 20Z', pause: 'M8 5v14M16 5v14', stop: 'M6 6h12v12H6Z', save: 'M5 3h12l4 4v14H3V3Zm2 0v7h10V3M7 21v-7h10v7', settings: 'M12 8a4 4 0 1 0 0 8 4 4 0 0 0 0-8M12 2v3M12 19v3M2 12h3M19 12h3M5 5l2 2M17 17l2 2M5 19l2-2M17 7l2-2', fit: 'M8 3H3v5M16 3h5v5M3 16v5h5M21 16v5h-5', upload: 'M12 16V3m-5 5 5-5 5 5M4 16v5h16v-5', download: 'M12 3v13m-5-5 5 5 5-5M4 17v4h16v-4' };
    return <svg aria-hidden="true" className="icon" viewBox="0 0 24 24"><path d={paths[name]} fill={name === 'play' || name === 'stop' ? 'currentColor' : 'none'} stroke="currentColor" strokeWidth="1.6" strokeLinecap="round" strokeLinejoin="round"/></svg>;
}
const fmt = (v: number, precision = 2) => (Math.abs(v) < 0.5 * 10 ** -precision ? 0 : v).toFixed(precision);
export default function App() {
    const sim = useSimulator(), s = sim.state, [dialog, setDialog] = useState<'settings' | 'help' | null>(null);
    const [showReach, setReach] = useState(true), [showTrail, setTrail] = useState(true), [showLabels, setLabels] = useState(true), [fitRadius, setFitRadius] = useState(s.robot.l1 + s.robot.l2);
    const [exportFile, setExportFile] = useState<{
        content: string;
        filename: string;
    } | null>(null);
    const [inputErrors, setInputErrors] = useState({ x: false, y: false, duration: false });
    const validity = (key: 'x' | 'y' | 'duration', valid: boolean) => { setInputErrors(previous => previous[key] === !valid ? previous : { ...previous, [key]: !valid }); if (!valid)
        sim.stop(); };
    const [name, setName] = useState(''), fileInput = useRef<HTMLInputElement>(null);
    useEffect(() => { setFitRadius(s.robot.l1 + s.robot.l2); }, [s.robot.l1, s.robot.l2]);
    const actual = forward(s.robot, s.pose), ik = inverse(s.robot, s.target, s.pose), selected = branchPose(ik, s.branch), singular = singularity(s.pose);
    const active = s.motion?.status === 'running' || s.motion?.status === 'paused', running = s.motion?.status === 'running', paused = s.motion?.status === 'paused';
    // The selected IK branch describes the destination. During playback, direct stored joints own the path.
    const invalid = inputErrors.x || inputErrors.y || (!active && !selected), canMove = !!selected && !inputErrors.x && !inputErrors.y && !inputErrors.duration, status = running ? 'Animating' : paused ? 'Paused' : invalid ? 'Invalid target' : 'Ready';
    const invalidMessage = inputErrors.x || inputErrors.y ? 'Enter finite x and y coordinates within ±100,000 mm. The arm remains at its last valid pose.' : !ik.ok ? ik.message : 'The selected branch is excluded by joint limits. Choose the other configuration.';
    const error = distance(actual.tip, s.target), progress = s.motion ? motionSample(s.motion).progress : 0;
    const excluded = s.waypoints.some(w => !poseValid(w.pose, s.robot));
    const saveWaypoint = () => { if (s.waypoints.length >= MAX_WAYPOINTS)
        return; const waypointName = name.trim() || `Pose ${s.waypoints.length + 1}`; sim.waypoints([...s.waypoints, { id: crypto.randomUUID(), name: waypointName, pose: [...s.pose] }]); setName(''); sim.notify(`Saved “${waypointName}” as joint angles.`); };
    const changeBranch = (branch: Branch) => sim.targetCommand(s.target, true, branch);
    return <div className="app-shell">
    <header className="app-header"><div className="brand"><svg aria-hidden="true" className="brand-mark" viewBox="0 0 40 40"><path d="M8 31 18 10 31 20"/><circle cx="18" cy="10" r="4"/><circle cx="31" cy="20" r="3"/></svg><div><h1>ArmLab<span className="version">01</span></h1><p>Interactive robot kinematics</p></div></div><div className="header-actions"><span className="model-tag">PLANAR 2R</span><button onClick={() => setDialog('help')} className="help-button" aria-label="Open help">?</button><button onClick={() => setDialog('settings')}><Icon name="settings"/><span>Robot settings</span></button><button onClick={() => fileInput.current?.click()}><Icon name="upload"/><span>Import</span></button><button onClick={() => { setExportFile({ content: JSON.stringify(sim.exportSession(), null, 2), filename: 'armlab-session.json' }); }}><Icon name="download"/><span>Export JSON</span></button></div></header>
    <input ref={fileInput} hidden type="file" accept=".json,application/json" aria-label="Import session file" onChange={async (e) => { const file = e.target.files?.[0]; e.target.value = ''; if (!file)
        return; try {
        if (file.size > MAX_FILE_BYTES)
            throw new Error('Session file exceeds 256 KB.');
        sim.load(parseSession(await file.text()));
    }
    catch (err) {
        sim.notify(`Import failed: ${(err as Error).message}`);
    } }}/>
    <div className="workspace-heading"><div><span className="eyebrow">SIMULATOR</span><h2>Planar arm workspace</h2></div><div className={`status status-${status.toLowerCase().replace(' ', '-')}`} role="status"><span />{status}</div></div>
    <main className="workbench">
      <aside className="control-column">
        <section className="panel joint-panel"><div className="panel-title"><h3>Joint control</h3><span className="panel-meta">FORWARD KINEMATICS</span></div>
          {s.pose.map((angle, i) => <div className={`joint-control joint-${i + 1}`} key={`${i}-${s.revision}`}><div className="joint-title"><span><i />{i === 0 ? 'Shoulder' : 'Elbow'}</span><span className="math">θ{i === 0 ? '₁' : '₂'}</span></div><NumberField label={`Joint ${i + 1} angle`} value={degrees(angle)} unit="°" min={degrees(s.robot.limits[i].min)} max={degrees(s.robot.limits[i].max)} onValue={v => { const pose = [...s.pose] as Pose; pose[i] = radians(v); sim.manual(pose); }}/><input type="range" aria-label={`Joint ${i + 1} slider`} min={degrees(s.robot.limits[i].min)} max={degrees(s.robot.limits[i].max)} step="0.1" value={degrees(angle)} disabled={s.robot.limits[i].min === s.robot.limits[i].max} onChange={e => { const pose = [...s.pose] as Pose; pose[i] = radians(Number(e.target.value)); sim.manual(pose); }}/><div className="range-labels"><span>{fmt(degrees(s.robot.limits[i].min), 0)}°</span><span>{i === 0 ? 'absolute' : 'relative to link 1'}</span><span>{fmt(degrees(s.robot.limits[i].max), 0)}°</span></div></div>)}
          <p className="help-note">Positive angles rotate counterclockwise. Joint edits update the arm immediately.</p>
        </section>
        <section className="panel target-panel"><div className="panel-title"><h3>Cartesian target</h3><span className="small-target">⌖</span></div><div className="two-fields" key={s.revision}><NumberField label="Target x" onValidity={v => validity('x', v)} value={s.target.x} onValue={x => sim.targetCommand({ ...s.target, x }, false)} min={-100000} max={100000} unit="mm"/><NumberField label="Target y" onValidity={v => validity('y', v)} value={s.target.y} onValue={y => sim.targetCommand({ ...s.target, y }, false)} min={-100000} max={100000} unit="mm"/></div><p className="help-note">Drag to solve live. Numeric entry stages a destination for either action below.</p>
          <div className="field-heading">IK configuration <span>{ik.solutions.length === 1 && ik.solutions[0].branches.length === 2 ? 'branches merged' : 'elbow bend'}</span></div><div className="branch-selector">{(['positive', 'negative'] as Branch[]).map(branch => <button key={branch} className={s.branch === branch ? 'selected' : ''} aria-pressed={s.branch === branch} onClick={() => changeBranch(branch)}><svg aria-hidden="true" viewBox="0 0 40 25"><path d={branch === 'positive' ? 'M4 20 16 5 36 20' : 'M4 5 16 20 36 5'}/><circle cx="16" cy={branch === 'positive' ? '5' : '20'} r="2"/></svg><span>{branch === 'positive' ? 'Positive' : 'Negative'}<small>sin θ₂ {branch === 'positive' ? '≥' : '≤'} 0</small></span></button>)}</div>
          <div className="target-actions"><button disabled={!canMove} onClick={() => sim.targetCommand(s.target, true)}>Solve now</button><button className="primary" disabled={!canMove} onClick={sim.animateTarget}><Icon name="play"/>Animate target</button></div>
        </section>
      </aside>
      <div className="simulation-column">
        <section className="canvas-panel"><div className="canvas-toolbar"><div><span className="canvas-dot"/>WORLD FRAME <span className="muted">/ mm</span></div><div className="zoom-controls"><button className="text-button" aria-label="Zoom out" onClick={() => setFitRadius(r => Math.min(r * 1.25, (s.robot.l1 + s.robot.l2) * 4))}>−</button><span>{Math.round((s.robot.l1 + s.robot.l2) / fitRadius * 100)}%</span><button className="text-button" aria-label="Zoom in" onClick={() => setFitRadius(r => Math.max(r / 1.25, (s.robot.l1 + s.robot.l2) * 0.4))}>+</button><button className="text-button" onClick={() => setFitRadius(s.robot.l1 + s.robot.l2)}><Icon name="fit"/>Fit view</button></div></div><RobotCanvas robot={s.robot} pose={s.pose} target={s.target} ik={ik} branch={s.branch} trail={s.trail} showReach={showReach} showTrail={showTrail} showLabels={showLabels} fitRadius={fitRadius} onTarget={p => sim.targetCommand(p, true)} invalid={!selected}/><div className="canvas-caption"><span><i className="legend-one"/>Link 1</span><span><i className="legend-two"/>Link 2</span><span><i className="legend-target"/>Target</span><span className="alt-legend">┄ Alternate IK</span></div><div className="view-options"><label><input type="checkbox" checked={showReach} onChange={e => setReach(e.target.checked)}/>Reach region</label><label><input type="checkbox" checked={showTrail} onChange={e => setTrail(e.target.checked)}/>Trail</label><label><input type="checkbox" checked={showLabels} onChange={e => setLabels(e.target.checked)}/>Labels</label><button className="text-button" onClick={sim.clearTrail} disabled={!s.trail.length}>Clear trail</button></div><p className="canvas-footnote">Geometric reach only · shading does not account for joint limits</p></section>
        <section className="panel motion-panel"><div className="panel-title"><h3>Motion transport</h3><span className="panel-meta">JOINT SPACE</span></div><div className="transport-row"><button className="transport-play" aria-label={paused ? 'Resume animation' : running ? 'Pause animation' : 'Play target animation'} disabled={!active && !canMove} onClick={active ? sim.togglePause : sim.animateTarget}><Icon name={running ? 'pause' : 'play'}/></button><button className="transport-stop" aria-label="Stop animation" disabled={!active} onClick={sim.stop}><Icon name="stop"/></button><div className="transport-progress"><div className="progress-text"><span>{s.motion ? `${fmt(s.motion.elapsedMs / 1000, 2)} / ${fmt(totalMs(s.motion) / 1000, 2)} s` : 'Ready for a destination'}<small>{s.motion && ` · segment ${motionSample(s.motion).segment + 1}/${s.motion.poses.length - 1}`}</small></span><span>{fmt(progress * 100, 0)}%</span></div><progress value={progress} max="1" aria-label="Motion progress"/></div><NumberField key={s.revision} label="Segment duration" onValidity={v => validity('duration', v)} value={s.duration} onValue={sim.duration} min={0.25} max={10} step={0.25} unit="s" disabled={active}/></div><div className="motion-footer"><span className="help-note">Cubic easing · zero endpoint speed · joint path, not generally a straight tip path</span><button className="text-button" disabled={!s.recording.length} onClick={() => { setExportFile({ content: samplesCsv(s.recording), filename: 'armlab-motion.csv' }); }}><Icon name="download"/>CSV <span className="sample-count">{s.recording.length}</span></button></div>{s.recording.length >= MAX_SAMPLES && <p className="field-error">Recording holds the latest 12,000 samples.</p>}</section>
      </div>
      <aside className="inspector-column"><section className="panel inspector-panel"><div className="panel-title"><h3>Numerical inspector</h3><span className="live-label">LIVE</span></div><div className="tip-coordinates"><span className="eyebrow">END EFFECTOR</span><div><span>x <strong data-testid="actual-x">{fmt(actual.tip.x)}</strong><small>mm</small></span><span>y <strong data-testid="actual-y">{fmt(actual.tip.y)}</strong><small>mm</small></span></div></div><table className="coordinates-table"><thead><tr><th>Position</th><th>x / mm</th><th>y / mm</th></tr></thead><tbody><tr><th>Target</th><td>{fmt(s.target.x)}</td><td>{fmt(s.target.y)}</td></tr><tr><th>Actual tip</th><td>{fmt(actual.tip.x)}</td><td>{fmt(actual.tip.y)}</td></tr><tr><th>Elbow</th><td>{fmt(actual.elbow.x)}</td><td>{fmt(actual.elbow.y)}</td></tr></tbody></table><div className={`error-readout ${invalid ? 'error-readout-invalid' : ''}`}><span>Position error</span><strong data-testid="position-error">{fmt(error, 3)} <small>mm</small></strong></div><div className="inspector-details"><span>Tool orientation <strong>{fmt(degrees(s.pose[0] + s.pose[1]), 1)}°</strong></span><span>Reach radii <strong>{fmt(Math.abs(s.robot.l1 - s.robot.l2), 0)}–{fmt(s.robot.l1 + s.robot.l2, 0)} mm</strong></span></div>{singular && <div className="singular-note"><strong>{singular === 'extended' ? 'Extended' : 'Folded'} singularity</strong><p>Local Cartesian motion capability is reduced. This pose can still be valid.</p></div>}{ik.degenerate && <p className="help-note">{ik.message}</p>}</section>
      <section className="panel waypoint-panel"><div className="panel-title"><h3>Waypoints <span className="count-badge">{s.waypoints.length}</span></h3><button className="text-button" onClick={sim.demo}>Load demo</button></div><div className="waypoint-save"><input aria-label="Waypoint name" placeholder="Name this pose…" maxLength={40} value={name} onChange={e => setName(e.target.value)} onKeyDown={e => { if (e.key === 'Enter')
        saveWaypoint(); }}/><button aria-label="Save current pose as waypoint" disabled={s.waypoints.length >= MAX_WAYPOINTS} onClick={saveWaypoint}>+</button></div><div className="waypoint-list">{!s.waypoints.length ? <div className="empty-state"><svg aria-hidden="true" viewBox="0 0 80 36"><path d="M8 27 30 9 52 27 72 9"/><circle cx="8" cy="27" r="3"/><circle cx="30" cy="9" r="3"/><circle cx="52" cy="27" r="3"/><circle cx="72" cy="9" r="3"/></svg><strong>A sequence starts with a pose.</strong><p>Save your current joints, or load the four-pose pick-and-place motion demo.</p></div> : s.waypoints.map((w, i) => { const valid = poseValid(w.pose, s.robot); return <div className={`waypoint ${!valid ? 'waypoint-excluded' : ''}`} key={w.id}><span className="waypoint-index">{String(i + 1).padStart(2, '0')}</span><button className="waypoint-pose" disabled={!valid} onClick={() => sim.start([w.pose])} title="Animate to this waypoint"><strong>{w.name}</strong><small>{fmt(degrees(w.pose[0]), 1)}° / {fmt(degrees(w.pose[1]), 1)}°{!valid && ' · excluded by limits'}</small></button><button className="delete-waypoint" aria-label={`Delete waypoint ${i + 1}: ${w.name}`} onClick={() => sim.waypoints(s.waypoints.filter(p => p.id !== w.id))}>×</button></div>; })}</div><div className="waypoint-actions"><button className="primary" disabled={!s.waypoints.length || excluded || inputErrors.duration} onClick={() => sim.start(s.waypoints.map(w => w.pose))}><Icon name="play"/>Play sequence</button><button disabled={!s.waypoints.length} onClick={() => sim.waypoints([])}>Clear</button></div>{excluded && <p className="field-error">Some poses are excluded by current limits. Adjust limits or delete those poses to play.</p>}<p className="help-note">Stores joint angles. Link changes move the saved tip positions. Motion only; no gripping or contact physics.</p></section></aside>
    </main>
    <div className={`message-bar ${invalid ? 'message-error' : ''}`} role={invalid || s.notice.startsWith('Import failed') ? 'alert' : 'status'}><span className="message-symbol">{invalid ? '!' : 'i'}</span><span>{invalid ? invalidMessage : s.notice || 'Drag the target or adjust a joint to explore. Load the demo for a ready-to-play sequence.'}{invalid && s.notice.startsWith('Import failed') ? ` ${s.notice}` : ''}</span>{s.notice && !invalid && <button aria-label="Dismiss message" onClick={() => sim.notify('')}>×</button>}</div>
    <footer className="app-footer"><span>ARMLAB / 2R KINEMATICS</span><span>Ideal rigid links · browser calculations · no physics simulation</span><button className="text-button" onClick={sim.reset}>Reset session</button></footer>
    {exportFile && <ExportDialog {...exportFile} onClose={() => setExportFile(null)}/>}
    {dialog === 'settings' && <SettingsDialog robot={s.robot} onSave={sim.settings} onReset={sim.reset} onClose={() => setDialog(null)}/>}{dialog === 'help' && <HelpDialog onClose={() => setDialog(null)}/>}
  </div>;
}
